merge to HEAD as of 2006-08-21

diff --git a/mkfedora b/mkfedora
--- a/mkfedora
+++ b/mkfedora
@@ -13,7 +13,7 @@
 # Mark Huang <mlhuang@cs.princeton.edu>
 # Copyright (C) 2004-2006 The Trustees of Princeton University
 #
-# $Id: mkfedora,v 1.17 2006/07/17 21:25:42 mlhuang Exp $
+# $Id: mkfedora,v 1.20 2006/08/16 01:56:06 mlhuang Exp $
 #
 
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -23,12 +23,11 @@ verbose=0
 
 # Default yum repositories to try
 mirrors=(
-file:///usr/share/mirrors/fedora
-file:///var/www/html/mirrors/fedora
-ftp://smoke.cs.princeton.edu/pub/mirrors/fedora
-ftp://128.112.137.30/pub/mirrors/fedora
+file:///data/fedora
 http://coblitz.planet-lab.org/pub/fedora
 ftp://mirror.cs.princeton.edu/pub/mirrors/fedora
+ftp://mirror.stanford.edu/pub/mirrors/fedora
+ftp://rpmfind.net/linux/fedora
 )
 
 # Release and architecture to install
@@ -327,15 +326,22 @@ yum -c $vroot/etc/yum.conf --installroot=$vroot -y $excludes install glibc
 
 # Go, baby, go
 if [ ${#packages[*]} -gt 0 ] ; then
-    echo "* Installing optional packages" >&3
-    yum -c $vroot/etc/yum.conf --installroot=$vroot -y $excludes \
-	install "${packages[@]}"
+   echo "* Installing optional packages" "${packages[@]}" >&3
+   yum -c $vroot/etc/yum.conf --installroot=$vroot -y $excludes \
+	  install "${packages[@]}"
+   if ! rpm --root $vroot -q "${packages[@]}" >/dev/null ; then
+       echo "* Warning: Missing packages"
+       rpm --root $vroot -q "${packages[@]}" | grep "not installed"
+   fi
 fi
 
 if [ ${#groups[*]} -gt 0 ] ; then
-    echo "* Installing optional groups" >&3
-    yum -c $vroot/etc/yum.conf --installroot=$vroot -y $excludes \
-	groupinstall "${groups[@]}"
+   ## call yum sequentially to get finer-grained info on dependencies
+   for grp in "${groups[@]}" ; do
+      echo "* Installing optional group $grp" >&3
+      yum -c $vroot/etc/yum.conf --installroot=$vroot -y $excludes \
+	groupinstall "$grp"
+   done
 fi
 
 # FC2 dev %preinstall checks /proc/mounts to make sure that /dev is
